### ISSUE TITLE
[FEATURE]: Separate `deepdiff` package from core deps packages

### ISSUE THREAD

**Issue by korawica** [korawica/ddeutil-io#47]
From the deps list in the pyproject file, it needs to install the `deepdiff` package, but it has only the Register module using this package.

```toml
dependencies = [
    "ddeutil==0.4.6",
    "fmtutil==1.0.15",
    "tzdata==2025.2",
    "deepdiff==8.4.2",
]
```
