### ISSUE TITLE
[Bug]: Resolve YAML raise key does not exist

### ISSUE THREAD

**Issue by korawica** [korawica/ddeutil-io#49]
From the test case of the Workflow project, it has a parallel stage to read this YAML file on a different thread.

```yaml
tmp-wf-parallel-trigger-raise-task:
  type: Workflow
  params:
    branch: str
  jobs:
    first-job:
      stages:
        - name: "Echo"
          id: raise-stage
          raise: "Raise trigger with branch: ${{ params.branch }}"

tmp-wf-parallel-trigger-raise:
  type: Workflow
  jobs:
    first-job:
      stages:
        - name: "Start run parallel stage"
          id: parallel-stage
          parallel:
            branch01:
              - name: "Stage trigger 1"
                trigger: "tmp-wf-parallel-trigger-raise-task"
                params:
                  branch: ${{ branch }}
            branch02:
              - name: "Stage trigger 2"
                trigger: "tmp-wf-parallel-trigger-raise-task"
                params:
                  branch: ${{ branch }}
```

Raise error statement:

```text
        revert = Resolver.yaml_implicit_resolvers.copy()
    
        for ch in "OoYyNn":
>           if len(Resolver.yaml_implicit_resolvers[ch]) == 1:
E           KeyError: 'O'
```
